### ISSUE TITLE
General: File Naming Conventions

### ISSUE THREAD

**Issue by aubricus** [ebramanti/Marionette-Todo#1]
### Description

Your naming conventions are a bit all over the place.

This wasn't called out explicitly; though the files in the sample project do follow a consistent naming convention.
### Suggested Improvement

Please follow this file/folder naming convention:

```
name-lower-case-with-dashes
```
### Reference Links
- https://github.com/jadengore/Marionette-Todo/tree/master/src/static/js/app/views
- https://github.com/jadengore/Marionette-Todo/tree/master/src/static/js/app/collections
- https://github.com/jadengore/Marionette-Todo/tree/master/src/static/js/app/templates

**Comment by ebramanti** [comment]
Following convention of lowercase w/ dashes from now on, updated files accordingly

**Comment by aubricus** [comment]
Looks fixed!
