### ISSUE TITLE
General: End of Line Comments

### ISSUE THREAD

**Issue by aubricus** [ebramanti/Marionette-Todo#2]
### Description

This is 100% **NOT MEANT** to discourage leaving comments. Please leave copious amounts of [useful] comments.

I'm also ok with EOL commenting; however if they're more than one or two words please put the comments on the line above the code they reference.
### Suggested Improvement

Put long EOL comments above the line they reference.
### Reference Link

https://github.com/jadengore/Marionette-Todo/blob/master/src/static/js/app/views/TaskCreationView.js

**Comment by ebramanti** [comment]
Moved comments in (now-renamed) task-creation-view up one line instead of having long-running EOL comments.

**Comment by aubricus** [comment]
Looks good.
