### ISSUE TITLE
General: Re-definition of Constants

### ISSUE THREAD

**Issue by aubricus** [ebramanti/Marionette-Todo#3]
## Code In Question

```
var ENTER_KEY = 13; //http://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes
```
## Description

While I do appreciate the readable variable declaration, you're re-defining this a couple times through your app (see reference links).

Additionally, The UPPERCASE_CONVENTION denotes a **constant**; but it's a bit of an anti-pattern to keep re-defining constants. 
## Suggested Improvement

Create require module(s) to store constant values. For example:

```
// enums/keys.js

exports.keys = {
  ENTER_KEY: 13
};
```

```
// some-other-file.js

keys = require('path/to/enums/keys.js).keys;

// .. some useful code
if(event.which == keys.ENTER_KEY)
```
## Reference Links
- https://github.com/jadengore/Marionette-Todo/blob/master/src/static/js/app/views/task-creation-view.js
- https://github.com/jadengore/Marionette-Todo/blob/master/src/static/js/app/views/task-item-view.js#L40-L44

**Comment by ebramanti** [comment]
Thanks for this, it didn't make sense doing it the way I did. Modularizing constants using require is awesome.
