### ISSUE TITLE
Task.js: Odd Status Property

### ISSUE THREAD

**Issue by aubricus** [ebramanti/Marionette-Todo#4]
## Code in Question

```
return this.get('status') === 'active' ? this.set('status', 'completed') : this.set('status', 'active')
```
### Description

There's a couple of things here:
1. This is way too much code for a ternary.
2. You're doing a lot of work here, that actually causes you to do even more work later.
#### Ternary Statements:

Limit ternary statements to short, readable code.

```
var nextIndex = this.index++
var shouldContinue = nextIndex < this.maxIndex ? true : false;
```
#### Status Property

To me this status property could be greatly simplified if it were renamed to `isActive` and set to `true` or `false`. Honestly; unless you think that Status will have more than 2 states; a  boolean value will suffice here.

Your `changeStatus` is really a toggle, so I'd rename it `toggleIsActive` and the function body would be reduced to:

```
return !this.get('isActive')
```

Your current implementation is also causing you extra work down the line, see:

```
if (this.model.get('status') === 'completed') {
    this.$el.addClass('completed');
} else if (this.model.get('status') === 'active') {
    this.$el.addClass('active');
}
```

There's a couple issues with this code:
1. It's not DRY (Don't Repeat Yourself), you've repeated `this.model.get('status')`  a few times here.
2. You're also typing that status 'magic' string over and over. It would be better to create a module that exports something like `itemStatus.Active` and `itemStatus.Completed`.

Assuming you've changed your implementation to use `isActive`, here's the resulting check:

```
// onRender function body
var isActive = this.model.get('isActive');

if(isActive) {
    // useful code
}
else {
   // more useful code if is active is false
}
```

This code is much shorter and easier to read.
### Reference Links
- https://github.com/jadengore/Marionette-Todo/blob/master/src/static/js/app/models/task.js
- https://github.com/jadengore/Marionette-Todo/blob/master/src/static/js/app/views/task-item-view.js#L26-L30

**Comment by ebramanti** [comment]
Just updated both sections of code to represent active/completed as a boolean.
